const abnormalityLinks = {
    "Lobar": "https://www.ncbi.nlm.nih.gov/medgen/?term=lobar+pneumonia",
    "Cavitations": "https://www.ncbi.nlm.nih.gov/medgen/612505",
    "Bronchiectasis": "https://www.ncbi.nlm.nih.gov/medgen/?term=bronchiectasis",
    "Hilar": "https://www.ncbi.nlm.nih.gov/medgen/?term=hilar+adenopathy",
    "Pleural Effusion": "https://www.nhlbi.nih.gov/health/pleural-effusion",
    "Military Opacities": "https://www.ncbi.nlm.nih.gov/medgen/?term=miliary+opacities",
    "Collapse": "https://www.ncbi.nlm.nih.gov/medgen/?term=lung+collapse",
    "Fibronodular": "https://www.ncbi.nlm.nih.gov/medgen/?term=fibronodular+infiltrates",
    "Pleural Thickening": "https://www.ncbi.nlm.nih.gov/medgen/?term=pleural+thickening",
    "Calcifications": "https://www.ncbi.nlm.nih.gov/medgen/?term=lung+calcifications",
    "Patchy Linear and Nodular Opacities": "https://www.ncbi.nlm.nih.gov/medgen/?term=patchy+opacities",
    "Fibrocalcific Opacities": "https://www.ncbi.nlm.nih.gov/medgen/?term=fibrocalcific+opacities",
    "Focal Segmental Opacities": "https://www.ncbi.nlm.nih.gov/medgen/?term=focal+segmental+opacities",
    "Bulging Fissure": "https://www.ncbi.nlm.nih.gov/medgen/?term=bulging+fissure+sign",
    "Lung Abscess": "https://www.ncbi.nlm.nih.gov/medgen/?term=lung+abscess",
    "Air Fluid Level": "https://www.ncbi.nlm.nih.gov/medgen/?term=air+fluid+level",
    "Parapneumonic Effusion": "https://www.nhlbi.nih.gov/health/pleural-effusion",
    "Pneumatocele": "https://www.ncbi.nlm.nih.gov/medgen/?term=pneumatocele",
    "Peribronchial Thickening": "https://www.ncbi.nlm.nih.gov/medgen/?term=peribronchial+thickening",
    "Interstitial Infiltrates": "https://www.ncbi.nlm.nih.gov/medgen/?term=interstitial+infiltrates",
    "Bronchopneumonia": "https://www.ncbi.nlm.nih.gov/medgen/?term=bronchopneumonia",
    "Irregular Nodule": "https://www.ncbi.nlm.nih.gov/medgen/?term=irregular+lung+nodule",
    "Spiculation": "https://www.ncbi.nlm.nih.gov/medgen/?term=spiculated+lung+nodule",
    "Hilar Mass": "https://www.ncbi.nlm.nih.gov/medgen/?term=hilar+mass",
    "Rib Erosion": "https://www.ncbi.nlm.nih.gov/medgen/?term=rib+erosion",
    "Tuberculosis": "https://www.nhlbi.nih.gov/health/tuberculosis",
    "Bacterial Pyrogenic Pneumonia": "https://www.ncbi.nlm.nih.gov/medgen/?term=bacterial+pneumonia",
    "Viral Pneumonia": "https://www.ncbi.nlm.nih.gov/medgen/?term=viral+pneumonia",
    "Lung Cancer": "https://www.cancer.gov/types/lung",
    "Normal Chest X-Ray": "https://medlineplus.gov/ency/article/003804.htm",
    "Abnormal Chest X-Ray": "https://medlineplus.gov/ency/article/003805.htm",
    "Hyperinflation": "https://www.ncbi.nlm.nih.gov/medgen/?term=lung+hyperinflation",
    "Destroyed Lungs": "https://www.ncbi.nlm.nih.gov/medgen/?term=destroyed+lung+syndrome",
    "Flattened Diaphragm": "https://www.ncbi.nlm.nih.gov/medgen/?term=flattened+diaphragm",
    "Nodular Infiltrates": "https://www.ncbi.nlm.nih.gov/medgen/?term=nodular+infiltrates",
    "Cardiomegaly": "https://www.nhlbi.nih.gov/health/cardiomegaly",
    "Mediastinal Lymph Node": "https://www.ncbi.nlm.nih.gov/medgen/?term=mediastinal+lymphadenopathy",
    "Fibrosis": "https://www.nhlbi.nih.gov/health/pulmonary-fibrosis",
    "Tubular Heart": "https://www.ncbi.nlm.nih.gov/medgen/?term=tubular+heart",
    "Elevated Diaphragm": "https://www.ncbi.nlm.nih.gov/medgen/?term=elevated+diaphragm",
    "Subcostal Effusion": "https://www.ncbi.nlm.nih.gov/medgen/?term=subpulmonic+effusion",
    "Deviated Trachea": "https://www.ncbi.nlm.nih.gov/medgen/?term=tracheal+deviation",
    "Consolidation": "https://www.ncbi.nlm.nih.gov/medgen/?term=lung+consolidation",
    "Pleural Mass": "https://www.ncbi.nlm.nih.gov/medgen/?term=pleural+mass",
    "Reticular Opacities": "https://www.ncbi.nlm.nih.gov/medgen/?term=reticular+opacities",
    "Nodule": "https://www.ncbi.nlm.nih.gov/medgen/?term=lung+nodule",
    "Hydropneumothorax": "https://www.ncbi.nlm.nih.gov/medgen/?term=hydropneumothorax",
    "Pneumothorax": "https://www.nhlbi.nih.gov/health/pneumothorax",
    "Ground Glass Opacity": "https://www.ncbi.nlm.nih.gov/medgen/?term=ground+glass+opacity",
    "Fibrotic Scarring": "https://www.ncbi.nlm.nih.gov/medgen/?term=fibrotic+scarring"
  }


  export default abnormalityLinks;
