[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["test"]
python_files = ["test_*.py"]
addopts = "--import-mode=importlib -v"
asyncio_mode = "auto"
markers = [
    "sanity",
    "validation",
    "stress"
]
[tool.isort]
profile = "black"